### ISSUE TITLE
Zsepi emergency

### ISSUE THREAD

**Issue by LetsUpdate** [gombossb/1_csomag_zsepi#1]
I need zsepi now

But i have no unrar toolkit ath this moment😭

Where can i find the unrar.zip?

**Comment by gombossb** [comment]
![image](https://github.com/gombossb/1_csomag_zsepi/assets/22570934/8921c4c5-b777-467d-9e1f-f4548264b539)

**Comment by LetsUpdate** [comment]
☠️
